### ISSUE TITLE
What is 'vision_dataset'

### ISSUE THREAD

**Issue by pierowu** [extremebird/Hydra#2]
In Hydra_clip.py ,there is 'from vision_datasets import DatasetTypes'.
Is vision_datasets a third party library or something we need to download by ourselves?

**Comment by yhyun225** [comment]
Hi, thanks for the interest!

'vision_dataset' is a package that handles commonly used vision datasets for various purposes. For more details, please refer the below github link.

https://github.com/microsoft/vision-datasets

If you follow the environmental setting as we denoted on our githhub, 'vision_datasets' will be automatically installed in your environment. Thanks!

**Comment by pierowu** [comment]
Thank you for answering!
