### ISSUE TITLE
Dataset download 

### ISSUE THREAD

**Issue by pierowu** [extremebird/Hydra#3]
When vision_datasets try to download datasets in elevater benchmark , it seems that there are some internet issues with the download link.
![image](https://github.com/extremebird/Hydra/assets/61963313/099f1362-696d-49dd-8621-dd1346c6d5d5)
I've checked in official repo of the datasets. The downloading issue seems to bother a few people.
Do you mind share a copy of dataset in disk or something ?

**Comment by pierowu** [comment]
I've solved this problem by add SAS to the link, according to the issue in https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC/issues/11

Specifically, change links in following positions.
![image](https://github.com/extremebird/Hydra/assets/61963313/beda03c6-eef2-4ec2-90b0-873606db383b)
![image](https://github.com/extremebird/Hydra/assets/61963313/81ded86d-2008-4ff1-bf5b-7eedbf9de368)

**Comment by extremebird** [comment]
Thank you for your solution! We modify the link
